---
title: "Paulo Ferreira Naibert"
description: |
  Some Links I find Useful (or fun)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Interesting Links

- [nefin](http://nefin.com.br/)
- [r-bloggers](https://www.r-bloggers.com/)
- [r-econometrics](https://www.r-econometrics.com/)
- [Reproducible Finance](http://www.reproduciblefinance.com/)
- [statmethods](https://www.statmethods.net/)
- [rcpp](http://www.rcpp.org/)
- [Numerical Recipes](http://numerical.recipes/)
- [econwiki](http://econphd.econwiki.com/index.htm)
- [CVX - Convex Optimization](http://cvxr.com/)
- [tufte handout](https://rstudio.github.io/tufte/)
- [Ken French Data Library](https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html)

## Journals
- [R Journal](https://journal.r-project.org/)

## Personal Websites

- [Gabrielito](https://sites.google.com/site/gabrielitorm/home)
- [Brian Kernighan](https://www.cs.princeton.edu/~bwk/)
- [Chiu Yu Ko](https://kochiuyu.github.io/)
- [stoffer](https://www.stat.pitt.edu/stoffer/index.html)
- [Francis X. Diebold](https://www.sas.upenn.edu/~fdiebold/)
- [Yihui Xie](https://yihui.org/)
- [Matt Might](http://matt.might.net/)
- [John Cochrane](https://www.johnhcochrane.com/)
- [Grumpy Economist](https://johnhcochrane.blogspot.com/)
- [Eric Zivot](https://faculty.washington.edu/ezivot/index.htm)
- [Dennis M. Ritchie](https://www.bell-labs.com/usr/dmr/www/index.html)
- [Jesus Fernandez Villaverde](https://www.sas.upenn.edu/~jesusfv/index.html)
- [Rob Tibshirani](https://statweb.stanford.edu/~tibs/)
- [Ravi Jagannathan](https://www.kellogg.northwestern.edu/faculty/jagannathan/htm/)
- [Ken French](https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/index.html)
- [James D. Hamilton](https://econweb.ucsd.edu/~jhamilto/)

## Books
- [R for Data Science](https://r4ds.had.co.nz/)
- [dscl](https://www.datascienceatthecommandline.com/1e/)
- [ggplot2](https://ggplot2-book.org/)
- [cookbook-R](http://www.cookbook-r.com/)
- [cookbook-R graphs](http://www.cookbook-r.com/Graphs/)

## Specific Links
- [R profile](http://www.onthelambda.com/2014/09/17/fun-with-rprofile-and-customizing-r-startup/)
- [R profile statmethods](https://www.statmethods.net/interface/customizing.html)
- [TikZ examples](https://kochiuyu.github.io/programming/tikz/consumer/)
- [vim-R](https://www.freecodecamp.org/news/turning-vim-into-an-r-ide-cd9602e8c217/)
- [stoffer-Rissues](https://www.stat.pitt.edu/stoffer/tsa4/Rissues.htm)
- [stoffer-R-plots](https://www.stat.pitt.edu/stoffer/tsa4/tsgraphics.htm)
- [R-plot shades](https://www.r-bloggers.com/creating-shaded-areas-in-r/)
- [R-plot shaddes](http://www.alisonsinclair.ca/2011/03/shading-between-curves-in-r/)
- [Project-oriented workflow](https://www.r-bloggers.com/%f0%9f%93%81-project-oriented-workflow/)

## R packages
- [itsmr](https://cran.r-project.org/web/packages/itsmr/)
- [astsa](https://cran.r-project.org/web/packages/astsa/)
- [dygraphs](https://rstudio.github.io/dygraphs/)

## BCB
- [dados abertos](https://dadosabertos.bcb.gov.br/)
- [estatísticas](https://www.bcb.gov.br/estatisticas)
- [SGS R](https://gabrielrega.com/2017/07/26/baixando-series-diretamente-do-sgs-do-banco-central-pelo-r/)
- [Tesourro Transparente](https://www.tesourotransparente.gov.br/)

# BEA
- [National](https://www.bea.gov/national/)
- [NIPA Primer](https://www.bea.gov/sites/default/files/methodologies/nipa_primer.pdf)
- [NIPA Handbook Website](https://www.bea.gov/resources/methodologies/nipa-handbook)
- [NIPA Handbook C.1-4 pdf](https://www.bea.gov/system/files/2019-12/Chapter-1-4.pdf)

## SIDRA IBGE
- [SIDRA](https://sidra.ibge.gov.br/)
- [SIDRA CNT](https://sidra.ibge.gov.br/home/cnt)
- [SIDRA IPCA](https://sidra.ibge.gov.br/home/ipca)

## CNT
- [SIDRA CNT](https://sidra.ibge.gov.br/home/cnt)
- [Natinal Accounts](https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais.html)
- [SCNT -- Quarterly](https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9300-contas-nacionais-trimestrais.html?=&t=o-que-e)
- [SCN -- Annual](https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9052-sistema-de-contas-nacionais-brasil.html?=&t=o-que-e)

### CNT Releases
- [CNT releases](https://biblioteca.ibge.gov.br/index.php/biblioteca-catalogo?view=detalhes&id=72121)
- [CNT 2020:Q1 release](https://biblioteca.ibge.gov.br/visualizacao/periodicos/2121/cnt_2020_1tri.pdf)
- [CNT 2020:Q2 release](https://biblioteca.ibge.gov.br/visualizacao/periodicos/2121/cnt_2020_2tri.pdf)

## System of National Accounts
- [UN SNA-2008](https://unstats.un.org/unsd/nationalaccount/docs/SNA2008.pdf)
- [IMF Quarterly National Accounts](https://www.imf.org/external/pubs/ft/qna/pdf/2017/QNAManual2017text.pdf)
- [BPM6 pdf](https://www.imf.org/external/pubs/ft/bop/2007/pdf/BPM6.pdf)
- [BPM6 website](https://www.imf.org/external/pubs/ft/bop/2007/bopman6.htm)
